name: Install Node and package dependencies
description: 'Install Node dependencies with pnpm'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2.2.1
      with:
        version: 7.9.5
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'pnpm'
    # * Install package dependencies. As cache is enabled, it will cache/restore downloaded files
    - shell: bash
      name: Install packages
      run: pnpm install --frozen-lockfile
