name: Nhost CLI
description: 'Action to install the Nhost CLI and to run an application'
inputs:
  start:
    description: "Start the application. If false, the application won't be started"
    default: 'false'
  wait:
    description: 'If starting the application, wait until it is ready'
    default: 'true'
  stop:
    description: 'Stop the application'
    default: 'false'
  path:
    description: 'Path to the application'
    default: '.'
  version:
    description: 'Version of the Nhost CLI'
    default: 'latest'
  config:
    description: 'Values to be injected into nhost/config.yaml'

runs:
  using: 'composite'
  steps:
    - name: Check if Nhost CLI is already installed
      id: check-nhost-cli
      shell: bash
      # TODO check if the version is the same
      run: |
        if [ -z "$(which nhost)" ]
        then
            echo "installed=false" >> $GITHUB_OUTPUT
        else
            echo "installed=true" >> $GITHUB_OUTPUT
        fi
    - name: Install Nhost CLI
      if: ${{ steps.check-nhost-cli.outputs.installed == 'false' }}
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 3
        max_attempts: 10
        command: bash <(curl --silent -L https://raw.githubusercontent.com/nhost/cli/main/get.sh) ${{ inputs.version }}
    - name: Set custom configuration
      if: ${{ inputs.config }}
      shell: bash
      working-directory: ${{ inputs.path }}
      run: config="${{ inputs.config }}" yq -i '. *= env(config)' nhost/config.yaml
    - name: Start the application
      if: ${{ inputs.start == 'true' }}
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        echo HASURA_GRAPHQL_ADMIN_SECRET=nhost-admin-secret\\nHASURA_GRAPHQL_JWT_SECRET=nhost-graphql-jwt-secret\\nNHOST_WEBHOOK_SECRET=nhost-webhook-secret\\nGRAFANA_ADMIN_PASSWORD=grafana-admin-password > .secrets
        nhost up &
    - name: Wait for the app to be ready
      id: wait
      if: ${{ inputs.start == 'true' && inputs.wait == 'true' }}
      shell: bash
      working-directory: ${{ inputs.path }}
      continue-on-error: true
      run: |
        curl -sSf --connect-timeout 3 \
          --max-time 5 \
          --retry 300 \
          --retry-delay 1 \
          --retry-max-time 300 \
          --retry-connrefused \
          'https://local.hasura.nhost.run' > /dev/null
    - name: Log on failure
      if: steps.wait.outcome == 'failure'
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        nhost logs
        exit 1
    - name: Stop the application
      if: ${{ inputs.stop == 'true' }}
      shell: bash
      working-directory: ${{ inputs.path }}
      run: nhost down
