name: Nhost CLI
description: 'Install Nhost CLI'
inputs:
  start:
    description: 'Start the application'
    default: 'true'
  wait:
    description: 'If starting the application, wait for the app to be ready'
    default: 'true'
  stop:
    description: 'Stop the application'
    default: 'false'
  path:
    description: 'Path to the application'
    default: '.'
  version:
    description: 'Version of the Nhost CLI'
  config:
    description: 'Custom Nhost CLI config'

runs:
  using: 'composite'
  steps:
    # * Install Nhost CLI if a `nhost/config.yaml` file is found
    - name: Install Nhost CLI
      shell: bash
      run: curl --silent -L https://raw.githubusercontent.com/nhost/cli/main/get.sh | bash
    - name: Set custom configuration
      if: ${{ inputs.config }}
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        config="${{ inputs.config }}"
        for key in $(echo "$config" | yq '. | keys | .[]'); do
            value=$(echo "$config" | yq  -o=json ".\"$key\"")
            yq -i ".$key = $value" nhost/config.yaml
        done
    - name: Start the application
      if: ${{ inputs.start == 'true' }}
      shell: bash
      working-directory: ${{ inputs.path }}
      run: nhost dev --no-browser &
    - name: Wait for the app to be ready
      id: wait
      if: ${{ inputs.start == 'true' && inputs.wait == 'true' }}
      shell: bash
      working-directory: ${{ inputs.path }}
      continue-on-error: true
      run: |
        curl -sS --connect-timeout 5 \
          --max-time 10 \
          --retry-delay 1 \
          --retry-max-time 300 \
          --retry-connrefused \
          'http://localhost:9695'
    - name: Log on failure
      if: steps.wait.outcome == 'failure'
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        nhost logs
        exit 1
    - name: Stop the application
      if: ${{ inputs.stop == 'true' }}
      shell: bash
      working-directory: ${{ inputs.path }}
      run: nhost down
