name: Renovate

on:
  pull_request:
    branches: [main]
    types: [opened]
    paths-ignore:
      - 'assets/**'
      - '**.md'
      - 'LICENSE'
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: nhost

jobs:
  renovate-changeset:
    name: Add changeset
    if: ${{ startsWith(github.head_ref, 'renovate/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      # * Install Node and dependencies. Package downloads will be cached for the next jobs.
      - name: Install Node and dependencies
        uses: ./.github/actions/install-dependencies
        with:
          TURBO_TOKEN: ${{ env.TURBO_TOKEN }}
          TURBO_TEAM: ${{ env.TURBO_TEAM }}
          BUILD: 'none'
      - name: Determine bumps
        id: bumps
        run: |
          echo "result<<EOF" >> $GITHUB_OUTPUT
          pnpm recursive list --depth -1 --parseable \
              --filter='!nhost-root' \
              --filter=[origin/main] \
              | xargs -I@ jq ".name" @/package.json \
              | sort \
              | uniq -u \
              | awk '$0=$0": patch"' \
              >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Install dictionary
        if: steps.bumps.outputs.result != ''
        run: sudo apt-get install wbritish
      - name: Generate changeset file name
        id: file_name
        if: steps.bumps.outputs.result != ''
        run: |
          FILE_NAME=$(shuf -n 3 /usr/share/dict/words | tr '\n' '-' | sed 's/-$//' | sed 's/'"'"'s//g' | tr '[:upper:]' '[:lower:]')
          echo "result=./.changeset/${FILE_NAME}.md" >> $GITHUB_OUTPUT
      - name: Create changeset file
        if: steps.bumps.outputs.result != ''
        run: |
          cat <<EOF > ${{ steps.file_name.outputs.result }}
          ---
          ${{ steps.bumps.outputs.result }}
          ---

          ${{ github.event.pull_request.title }}
          EOF
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.bumps.outputs.result != ''
        with:
          commit_message: ${{ github.event.pull_request.title }}
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true
